EProjectGroup2/Models/DataTransferObject/UserModelDto/AddUserModelDto.cs
using Microsoft.AspNetCore.Identity;

namespace EProjectGroup2.Models.DataTransferObject.UserModelDto
{
    public class AddUserModelDto : IdentityUser<int>
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string? Description { get; set; }
        public string? FullName { get; set; }
        public DateTime? DoB { get; set; }
        public string? Sex { get; set; }
        public string? Email { get; set; }
        public string? Address { get; set; }
        public string? Phone { get; set; }
        public bool? IsAdmin { get; set; }
        public bool Status { get; set; }
        public bool IsDelete { get; set; }
    }
}

EProjectGroup2/Models/EducationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace EProjectGroup2.Models
{
    public class EducationModel
    {
        [Key]
        public int EducationId { get; set; }
        public string? EducationName { get; set; }
        public string? ShortDescription { get; set; }
        public string? Description { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool Status { get; set; }
        public bool IsDelete { get; set; }
        public int? UserID { get; set; }
        public virtual UserModel? Users { get; set; }
    }
}

EProjectGroup2/Models/ErrorViewModel.cs
namespace EProjectGroup2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EProjectGroup2/Models/MedicalEquipmentModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace EProjectGroup2.Models
{
    public class MedicalEquipmentModel
    {
        [Key]
        public int MedicalEquipmentID { get; set; }
        public string? MedicalEquipmentName { get; set; }
        public int? MedicalEquipmentType { get; set; }
        public string? Description { get; set; }
        public int? Quantity { get; set; }
        public float? Price { get; set; }
        public string? ImagePath { get; set; }
        public DateTime? ImportDate { get; set; }
        public DateTime? ManufacturedDate { get; set; }
        public string? Manufacturer { get; set; }
        public bool Status { get; set; }
        public bool IsDelete { get; set; }
        public virtual ICollection<ReviewsModel>? Reviews { get; set; }
        public virtual ICollection<OrdersModel>? Orders { get; set; }
    }
}

EProjectGroup2/Models/OrdersModel.cs
using System.ComponentModel.DataAnnotations;

namespace EProjectGroup2.Models
{
    public class OrdersModel
    {
        [Key]
        public int OrderID { get; set; }
        public int? UserID { get; set; }
        public int? MedicalEquipmentID { get; set; }
        public int? PharmacyID { get; set; }
        public DateTime? CreatedDate { get; set; }
        public UserModel? Users { get; set; }
        public PharmacyModel? Pharmacies { get; set; }
        public MedicalEquipmentModel? MedicalEquipments { get; set; }
    }
}

EProjectGroup2/Models/PharmacyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace EProjectGroup2.Models
{
    public class PharmacyModel
    {
        [Key]
        public int PharmacyID { get; set; }
        public string? PharmacyName { get; set; }
        public string? Description { get; set; }
        public int? Quantity { get; set; }
        public float? Price { get; set; }
        public string? ImagePath { get; set; }
        public DateTime? ImportDate { get; set; }
        public DateTime? ExpireDate { get; set; }
        public DateTime? ManufacturedDate { get; set; }
        public string? Manufacturer { get; set; }
        public bool Status { get; set; }
        public bool IsDelete { get; set; }
        public virtual ICollection<ReviewsModel>? Reviews { get; set; }
        public virtual ICollection<OrdersModel>? Orders { get; set; }
    }
}

EProjectGroup2/Models/ReviewsModel.cs
using System.ComponentModel.DataAnnotations;

namespace EProjectGroup2.Models
{
    public class ReviewsModel
    {
        [Key]
        public int ReviewID { get; set; }
        public int? UserID { get; set; }
        public int? MedicalEquipmentID { get; set; }
        public int? PharmacyID { get; set; }
        public DateTime? CreatedDate { get; set; }
        public UserModel? Users { get; set; }
        public PharmacyModel? Pharmacies { get; set; }
        public MedicalEquipmentModel? MedicalEquipments { get; set; }
    }
}

EProjectGroup2/Models/UserLogin.cs
using System.ComponentModel.DataAnnotations;

namespace EProjectGroup2.Models
{
    public class UserLogin
    {
        [Key]
        public int UserID { get; set; }
        public string? UserName { get; set; }
        public string? Password { get; set; }
    }
}

EProjectGroup2/Models/UserModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace EProjectGroup2.Models
{
    public class UserModel
    { 
        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string? Description { get; set; }
        public string? FullName { get; set; }
        public DateTime? DoB { get; set; }
        public string? Sex { get; set; }
        public string? Email { get; set; }
        public string? Address { get; set; }
        public string? Phone { get; set; }
        public bool? IsAdmin { get; set; }
        public bool Status { get; set; }
        public bool IsDelete { get; set; }
        public virtual ICollection<EducationModel>? Educations { get; set; }
        public virtual ICollection<OrdersModel>? Orders { get; set; }
        public virtual ICollection<ReviewsModel>? Reviews { get; set; }
    }
}

EProjectGroup2/Controllers/HomeController.cs
using EProjectGroup2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EProjectGroup2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EProjectGroup2/Controllers/UsersController.cs
using EProjectGroup2.DataContext;
using EProjectGroup2.Models;
using EProjectGroup2.Models.DataTransferObject.UserModelDto;
using Microsoft.AspNetCore.Mvc;

namespace EProjectGroup2.Controllers
{
    public class UsersController : Controller
    {
        private readonly ClinicDataContext _clinicalDataContext;
        public UsersController(ClinicDataContext clinicDataContext)
        {
            _clinicalDataContext = clinicDataContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddUserModelDto userModelDto)
        {
            var user = new UserModel()
            {
                UserName = userModelDto.UserName,
                Email = userModelDto.Email,
                Address = userModelDto.Address,
                Description = userModelDto.Description,
                DoB = userModelDto.DoB,
                FullName = userModelDto.FullName,
                IsAdmin = userModelDto.IsAdmin,
                IsDelete = userModelDto.IsDelete,
                Password = userModelDto.Password,
                Phone = userModelDto.Phone,
                Sex = userModelDto.Sex,
                Status = userModelDto.Status,
            };
            await _clinicalDataContext.Users.AddAsync(user);
            await _clinicalDataContext.SaveChangesAsync();
            return RedirectToAction("Add");
        }
    }
}

EProjectGroup2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EProjectGroup2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EProjectGroup2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EProjectGroup2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EProjectGroup2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Add">Create User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>.
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EProjectGroup2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EProjectGroup2/Views/Users/Add.cshtml
@model EProjectGroup2.Models.DataTransferObject.UserModelDto.AddUserModelDto
@{
}
<form method="post" action="Add">
  <div class="mb-3">
    <label for="" class="form-label">UserName</label>
    <input type="text" class="form-control" asp-for="UserName" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">PassWord</label>
    <input type="text" class="form-control" asp-for="Password" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">FullName</label>
    <input type="text" class="form-control" asp-for="FullName" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">Description</label>
    <input type="text" class="form-control" asp-for="Description" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">Date of Birth</label>
    <input type="date" class="form-control" asp-for="DoB" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">Sex</label>
    <input type="text" class="form-control" asp-for="Sex" >
  </div>
    <div class="mb-3">
    <label for="" class="form-label">Email</label>
    <input type="email" class="form-control" asp-for="Email" >
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Address</label>
    <input type="text" class="form-control" asp-for="Address" >
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Phone</label>
    <input type="text" class="form-control" asp-for="Phone" >
  </div>
   <div class="mb-3">
    <label for="" class="form-label">IsAdmin</label>
    <input type="radio" class="form-control" asp-for="IsAdmin" value="false">
  </div>
   <div class="mb-3">
    <label for="" class="form-label">IsDelete</label>
    <input type="radio" class="form-control" asp-for="IsDelete"  value="false">
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Status</label>
    <input type="radio" class="form-control" asp-for="Status" value="true">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>